feat: endpoint option for hybris backend
amplience/dc-extension-product-selector pull request #16
Opened 2021-08-12 08:56 UTC by rs-amp

The endpoint that the `ycommercewebservices` endpoint is on might be different between hybris instances, depending on configuration. I've seen a few setups with `/occ/v2`, so it was worth adding this option just to support those cases.

The tests have been updated to check the correct endpoint is passed for both the default behaviour, and when `hybrisEndpoint` is specified in params. The hybris example has also been updated in the readme.

2022-06-10 10:23 UTC, pixelscript requested changes

2022-06-10 10:23 UTC, pixelscript commented on README.md
> +  "hybrisUrl": "{Endpoint for you hybris api (defaults to /rest/v2)}",
Readme should say `hybrisEndpoint`

2022-06-10 10:37 UTC, pixelscript approved these changes

2022-06-13 08:41 UTC, easen-amp approved these changes

2022-06-30 10:12 UTC, merged